### ISSUE TITLE
Improve the plugin by adding SSML support

### ISSUE THREAD

**Issue by lucoiso** [lucoiso/UEAzSpeech#11]
Issue created based on suggestions received in the [UE Forum](https://forums.unrealengine.com/t/free-azspeech-plugin-async-text-to-voice-and-voice-to-text-with-microsoft-azure/495394?u=lucoiso). : )

SSML = Speech Synthesis Markup Language.
Microsoft Docs: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup

**Comment by oivio** [comment]
I found another free plugin "Azure TTS" but it is abounded. It supposes to support SSML etc but, it is hard to find out why it does not work. At least it is something that I did try. Maybe it is worth looking into and maybe there is a way to analyze the code and integrate it with this amazing plugin? 
https://www.unrealengine.com/marketplace/en-US/product/azure-tts

**Comment by lucoiso** [comment]
Hi @oivio ! :)

[This commit](https://github.com/lucoiso/UEAzSpeech/commit/504a2ae8d5c0f02af16d12d1a6ba1ecab6e879cd) adds SSML support but I will check some ways to make it easier to use as Speech SDK uses the string and not the file as parameter, so I will have a look at some XML related UE functions or just implement a function to load the file and get your text string. 👀
