### ISSUE TITLE
About Nodes: The question of converting Audio Data To SoundWave

### ISSUE THREAD

**Issue by Gobcurry** [lucoiso/UEAzSpeech#141]
Hello, first of all, thank you very much for making this plug-in, which is very helpful.
Here are my questions:
When I use the "Convert Audio Data To SoundWave" node, what information do I need to fill in the Output Moudle Path, Relative Oytput Directory and Output Asset Name respectively? Every time I fill in the information, the node will crash after running. My audio Data Raw Data has been verified to be Valid. I hope you can answer my question.

Thank you very much!

**Comment by lucoiso** [comment]
Hi! @Gobcurry 

Sorry, these changes weren't explained well and i didn't updated the documentation yet.

You can let these values empty, and the function will create a transient/temporary sound wave to use.
You'll fill these values if you want to save in project's content directory.

About the parameters:
* Output Module Path: The name of the module that will own the generated soundwave. Can be **Game** or **/Game/** or the name of a plugin with content enabled. If you set to **Game**, the function will save the generated Sound Wave in your project content directory.
* Relative Output Directory: The relative directory to store the generated sound wave. If you set Module Path to **Game** and the output directory to **Testing**, the generated sound wave will be placed in PROJECT_DIRECTORY/Content/Testing (Content/Testing).
* Output Asset Name: The name of the generated sound wave.

## Example 1
Output Module Path: /Game/
Relative Output Directory: Generated_Sounds
Output Asset Name: SW_Generated_Audio

The function will create a sound wave in PROJECT_DIRECTORY/Content//Generated_Sounds/SW_Generated_Audio.uasset

## Example 2
Output Module Path: PluginWithContentEnabled
Relative Output Directory: Sounds
Output Asset Name: SW_Plugin_Audio_01

The function will create a sound wave in PROJECT_DIRECTORY/Plugins/PluginWithContentEnabled/Content/Sounds/SW_Plugin_Audio_01.uasset

---

I'll update the documentation soon and update the comment of these functions.
I'll also create a function to get the available modules to use.

The Editor Tool is using this function too and listing the available values if you want to check before using! :)

![image](https://user-images.githubusercontent.com/77353979/223111565-090008c4-b0e3-4cd5-a2f9-daef7369ba20.png)
_Tools -> AzSpeech -> Audio Generator_

**Comment by Gobcurry** [comment]
Thank you very much for your reply!
It was explained in great detail





Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lucoiso/UEAzSpeech"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 晚上8:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lucoiso/UEAzSpeech] About Nodes: The question of converting Audio Data To SoundWave (Issue #141)





 
Hi! @Gobcurry
 
Sorry, these changes weren't explained well and i didn't updated the documentation yet.
 
You can let these values empty, and the function will create a transient/temporary sound wave to use.
 You'll fill these values if you want to save in project's content directory.
 
About the parameters:
  
Output Module Path: The name of the module that will own the generated soundwave. Can be Game or /Game/ or the name of a plugin with content enabled. If you set to Game, the function will save the generated Sound Wave in your project content directory.
 
Relative Output Directory: The relative directory to store the generated sound wave. If you set Module Path to Game and the output directory to Testing, the generated sound wave will be placed in PROJECT_DIRECTORY/Content/Testing (Content/Testing).
 
Output Asset Name: The name of the generated sound wave.
  
Example 1
 
Output Module Path: /Game/
 Relative Output Directory: Generated_Sounds
 Output Asset Name: SW_Generated_Audio
 
The function will create a sound wave in PROJECT_DIRECTORY/Content//Generated_Sounds/SW_Generated_Audio.uasset
 
Example 2
 
Output Module Path: PluginWithContentEnabled
 Relative Output Directory: Sounds
 Output Asset Name: SW_Plugin_Audio_01
 
The function will create a sound wave in PROJECT_DIRECTORY/Plugins/PluginWithContentEnabled/Content/Sounds/SW_Plugin_Audio_01.uasset
 
 
I'll update the documentation soon and update the comment of these functions.
 I'll also create a function to get the available modules to use.
 
The Editor Tool is using this function too and listing the available values if you want to check before using! :)
 

 Tools -&gt; AzSpeech -&gt; Audio Generator
