### ISSUE TITLE
LogAzSpeech_Internal: Error: Thread: AzSpeech_SpeechToText_67870; Function: ProcessRecognitionResult; Message: Task failed. Reason: NoMatch

### ISSUE THREAD

**Issue by GGGHoliday** [lucoiso/UEAzSpeech#150]
What do I need to do？Please
And I have some questions，When I can use the Speech to Text，but I can't use the Text to Speech.
and When I can use Text to Speech,but I can't use the Speech to Text.
My unreal version is 4.27.  My country is China.Using VPN.

**Comment by lucoiso** [comment]
Hello @GGGHoliday ! :)

Looks like to use VPN, some extra work will be needed:

https://learn.microsoft.com/en-us/azure/cognitive-services/cognitive-services-virtual-networks?tabs=portal
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-services-private-link?tabs=portal

I'm already adding support for private endpoints in the plugin, So you'll can test using AzSpeech! :)

**Comment by lucoiso** [comment]
@GGGHoliday 

Can you test again using a private endpoint?

Project Settings -> Plugins -> AzSpeech -> Azure
Enable 'Use Private Endpoint' + Set your endpoint in 'Private Endpoint'

![image](https://user-images.githubusercontent.com/77353979/225371068-8c72066d-8141-4435-9371-ff269fdc8604.png)

**Comment by lucoiso** [comment]
@GGGHoliday 

Support for private endpoints is now in the main branch: https://github.com/lucoiso/UEAzSpeech
Release: https://github.com/lucoiso/UEAzSpeech/releases/tag/v1.5.0

**Comment by GGGHoliday** [comment]
Thanks，This question has been solved.
