### ISSUE TITLE
Can't Package with android?

### ISSUE THREAD

**Issue by JiangHaiWei** [lucoiso/UEAzSpeech#153]
When I try to package it in UE4.27(Android platform).Device show me this。How can I fix it?
![Screenshot_2023-03-16-00-17-38-95_6121f66d68a9010b51ee29f9b144fd14](https://user-images.githubusercontent.com/72482462/225374759-db032e92-24b0-42fb-b524-4390715f1200.jpg)

**Comment by JiangHaiWei** [comment]
I'm sore I did installed it!

**Comment by lucoiso** [comment]
Hi @JiangHaiWei ! :)

Are you using the marketplace or the github version? And can you provide the packaging logs?

**Comment by JiangHaiWei** [comment]
I fix it now.I rebuild the project.And It's work now,Thank you!
