### ISSUE TITLE
LogAudio: Warning: Wave data chunk is too big!

### ISSUE THREAD

**Issue by helloworld8686** [lucoiso/UEAzSpeech#160]
when I  call    ConvertAudioDataToSoundWave()
ue4  has warning.

**Comment by lucoiso** [comment]
> 

Hi @helloworld8686 ! :)

Can you send me your settings (**without your subscription**) and provide the project logs?

Enable logs in: Project Settings -> Plugins -> AzSpeech -> Enable SDK Logs + Enable Internal Logs
Logs are generated id: PROJECT_DIRECTORY/Saved/Logs and PROJECT_DIRECTORY/Saved/Logs/AzSpeech
