### ISSUE TITLE
How to Play TTS Sound while receiving blendshapes?

### ISSUE THREAD

**Issue by zixixr** [lucoiso/UEAzSpeech#169]
Hi I'm currently using get extracted animation data with synthesis completed node. For a reply that is long, for example, 100 words, you have to wait for the animation(blendshape data) array receiving for a long time then you can play the sound together with the animation.

Actually the sound could be generated much faster than a long blendshape array, so now the delay is very long in order to wait for the animation array to be generated. Is there a way that could eliminate the delay?

**Comment by Miru302** [comment]
I wonder where is the blendshape data coming from? I thought Azure Speech only returns sound wave?

In any case, it seems your bottleneck is blendshapes generation, which understandably starts only after sound is generated. If you are using something like MetahumanSDK to create blendshape animation from sound wave, you shoud check how streaming works in it (there are demo maps that showcase it).

On a side note, sound generation from Azure Speech Services can be streamed as well, and it's recommended if response speed is critical for your project. But it's going to be tricky to feed such buffer bits to generate animations, so probably not for this use case. But could be a good idea for UEAzSpeech in general? :)

**Comment by zixixr** [comment]
> I wonder where is the blendshape data coming from? I thought Azure Speech only returns sound wave?
> 
> In any case, it seems your bottleneck is blendshapes generation, which understandably starts only after sound is generated. If you are using something like MetahumanSDK to create blendshape animation from sound wave, you shoud check how streaming works in it (there are demo maps that showcase it). This will somewhat speed up the response time.
> 
> On a side note, sound generation from Azure Speech Services can be streamed as well, and it's recommended if response speed is critical for your project. But it's going to be tricky to feed such buffer bits to generate animations, so probably not for this use case. But could be a good idea for UEAzSpeech in general? :)

The Blendshape data comes from Azure, I'm doing my own lipsync based on that data, not through MetahumanSDK. And for long paragraph, it's very common that Azure takes way longer time for blendshapes generation than soundwavs.
