### ISSUE TITLE
Function: ProcessRecognitionResult; Message: Task failed. Reason: NoMatch

### ISSUE THREAD

**Issue by graslo** [lucoiso/UEAzSpeech#170]
I'm trying to diagnose a problem getting the plugin to recognize my audio. I'm not sure if it's an issue with my Azure setup or something else altogether.

When I use my mic with the plugin, I'm seeing this in the log:

LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_37203; Function: Run; Message: Starting recognition
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_37203; Function: Run; Message: Recognition started.
LogAzSpeech_Internal: Error: Thread: AzSpeech_SpeechToText_37203; Function: ProcessRecognitionResult; Message: Task failed. Reason: NoMatch
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_37203; Function: StopAzSpeechRunnableTask; Message: Setting runnable work as pending stop
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_37203; Function: Stop; Message: Stopping runnable thread work
LogAzSpeech: Display: Task: SpeechToText (37203); Function: StopAzSpeechTask; Message: Stopping task
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_37203; Function: StopAzSpeechRunnableTask; Message: Setting runnable work as pending stop
LogAzSpeech: Display: Task: SpeechToText (37203); Function: SetReadyToDestroy; Message: Setting task as Ready to Destroy

**Comment by ccxxww123** [comment]
I'm having the same problem,Do you have a solution？
