### ISSUE TITLE
closes whenever I don't use "Speech Default Options"

### ISSUE THREAD

**Issue by yvasquezmonoku** [lucoiso/UEAzSpeech#180]
I'm having trouble trying to assign a different voice for each character, when doing this the editor always closes.
![image](https://user-images.githubusercontent.com/38009822/228893623-6aa8c8f7-21a8-43a2-9b20-ddb58a8c737c.png)
![image](https://user-images.githubusercontent.com/38009822/228893906-cb765fd9-a691-4663-935c-e3ab2599d464.png)

**Comment by lucoiso** [comment]
Hello! :)

Can you check if this still occurs with the latest version? Made some changes to the params. Now you can change the voice inline with the task:

![image](https://user-images.githubusercontent.com/77353979/228896414-1312273d-94e9-4382-9211-2c53d1c6223e.png)

**Comment by yvasquezmonoku** [comment]
I am going to try

**Comment by yvasquezmonoku** [comment]
Sorry for the question, but what time should I put in these nodes?
![image](https://user-images.githubusercontent.com/38009822/228902005-a6a6effc-a667-4782-9780-60305dfce139.png)
![image](https://user-images.githubusercontent.com/38009822/228902092-e271f147-4845-42e7-adf7-8827e5b481c3.png)

**Comment by lucoiso** [comment]
If these values won't change, you can also use the Get AzSpeech Default Options and use the Subscription Options :)
