### ISSUE TITLE
How can I convert BlendShapes data to animations?

### ISSUE THREAD

**Issue by kqkq** [lucoiso/UEAzSpeech#182]
The plugin can return Viseme data in Blend Shapes, how can we make use of it? 

Can I convent it to an animation asset object to drive a Metahuman (lip sync)?

**Comment by lucoiso** [comment]
Hi! Sorry for the delay! :)

Never did this, but there's some tutorials in Youtube like this one using OVR Lip Sync: https://www.youtube.com/watch?v=j-nBVSl59ZA

**Comment by Liyi1998** [comment]
我也非常想得到这个答案
