### ISSUE TITLE
Break AzSpeechSettingsOptions in 1.6.5 does not expose settings anymore

### ISSUE THREAD

**Issue by aacloudguy** [lucoiso/UEAzSpeech#184]
As of 1.6.5, perhaps 1.6.4, in Break AzSpeechSettingsOptions, the outputs for Subscription Key, Region ID, Use Private Endpoint, Private Endpoint, and Profanity Filter no longer appear when you Refresh Node on the Blueprint. It's not possible to run the demo or use this node anymore. I've tried with the Marketplace version and with the downloaded Release version, though I'm not enough of a developer to know how to build my own copy.

It's an excellent plugin, and I love it. I'm using engine version 5.11 on Windows 11.

**Comment by lucoiso** [comment]
Hi @aacloudguy !
Sorry for the delay! :S 

The structures that are used as params were changed: https://user-images.githubusercontent.com/77353979/228281114-f11f5808-3ada-412e-a891-4d2826fffc00.png

The **AzSpeechSettingsOptions** now contains sub structures: Subscription Options, Recognition Options & Synthesis Options.

You can find the **Subscription Key, Region ID, Use Private Endpoint, Private Endpoint** in Subscription Options and **Profanity Filter** inside the Recognition & Synthesis Options.

If you still can't get these properties, maybe the engine didn't updated the changed correctly. You can try again recreating the nodes?
