### ISSUE TITLE
Missing `Microsoft.CognitiveServices.Speech.extension.codec.dll`?

### ISSUE THREAD

**Issue by debellica** [lucoiso/UEAzSpeech#194]
Hello :)

When packaging I am getting a missing dll error on the internal logs - and the pacakged project always fails to make the call to Azure (PIE works fine). Am I missing a component installation or has the lib missed something in compilation?

`LogInit: Display: LogAzSpeech_Internal: Warning: LogLastError: Failed to load runtime library "C:/Git/MyProject/Plugins/AzSpeech/Source/ThirdParty/AzureWrapper/libs/Win/Runtime/Microsoft.CognitiveServices.Speech.extension.codec.dll": 2 (The system cannot find the file specified.).`

Not quite sure when this started happening tbh. It worked in pacakged projects before.

**Comment by debellica** [comment]
Hmm yeah i just packaged SpeechGPT and the same error occurs - the packaging completes successfully but throws this error (can see it copying over at the beginning but then later on in the log this appears - not copied over correctly?) and then doesn't complete the speech request. It successfully fires Started but then Updated/Completed never fire. Failed doesn't fire also, because we are successful but incomplete.

`LogAzSpeech_Internal: Warning: LogLastError: Failed to load runtime library "C:/Git/thirdparty/lucosio/UESpeechGPT/Plugins/UEAzSpeech/Source/ThirdParty/AzureWrapper/libs/Win/Runtime/Microsoft.CognitiveServices.Speech.extension.codec.dll": 2 (The system cannot find the file specified.).`

**Comment by debellica** [comment]
![image](https://user-images.githubusercontent.com/20903421/232358363-ca856865-7cb5-44db-8dc0-c1165354916a.png)

**Comment by debellica** [comment]
This is all we get when we start a STT:

`LogAzSpeech: Display: Task: SpeechToText (242316); Function: Activate; Message: Activating task
LogAzSpeech_Internal: Display: Task: SpeechToText (242316); Function: StartAzureTaskWork; Message: Starting Azure SDK task
LogAzSpeech_Internal: Display: Task: SpeechToText (242316); Function: StartAzureTaskWork; Message: Using audio input device: Default
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: Init; Message: Initializing runnable thread
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: CanInitializeTask; Message: Checking if can initialize task in current context
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: Run; Message: Running runnable thread work
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: InitializeAzureObject; Message: Initializing Azure Object
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: InitializeAzureObject; Message: Creating recognizer object
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: CreateSpeechConfig; Message: Creating Azure SDK speech config
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: ApplySDKSettings; Message: Applying Azure SDK Settings
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: EnableLogInConfiguration; Message: Enabling Azure SDK log
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: InsertProfanityFilterProperty; Message: Adding profanity filter property
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: ApplySDKSettings; Message: Using language: Default
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: Run; Message: Starting recognition
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: Run; Message: Recognition started.`

Until we press stop and get the usual:

`LogAzSpeech: Display: Task: SpeechToText (242316); Function: StopAzSpeechTask; Message: Stopping task
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: StopAzSpeechRunnableTask; Message: Setting runnable work as pending stop
LogAzSpeech: Display: Task: SpeechToText (242316); Function: SetReadyToDestroy; Message: Setting task as Ready to Destroy
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: StopAzSpeechRunnableTask; Message: Setting runnable work as pending stop
LogAzSpeech_Internal: Display: Thread: AzSpeech_SpeechToText_242316; Function: Stop; Message: Stopping runnable thread work`

TTS seems to still work

**Comment by debellica** [comment]
Just using this node - Started is the only one that fires

![image](https://user-images.githubusercontent.com/20903421/232359574-9181a9c1-ef9f-4841-ba44-94352f2ed722.png)

**Comment by debellica** [comment]
After clearing all temporary files from the project and from all the plugins, I packaged the project and AzSpeech started working again. I will have to clear the cache more often with this plugin as it seems MS is quite heavy on the temp files and things must get easily corrupted. I still get the warning in the OP when packaging as you say, however... but this error is unrelated to what I originally thought it was. 

Thanks for the response!

**Comment by debellica** [comment]
Hmm but why did it not work on SpeechGPT? That's weird. I'll have to double check for you and get back to you about that. Might have been a me thing

**Comment by BlocksMonkey** [comment]
I appear to be having this same issue upgrading to the latest version of this plugin.
STT suddenly stopped working. I get the same error and log lines that @debellica reported earlier in the thread.
I don't appear to be getting any Azure logging even though I've Checked "Enable Azure SDK Logs"

I tried clearing the Intermediate folder from the AzSpeech plugin, and from the project without any luck.
Any suggestions? Or is there any other information I can provide?

**Comment by BlocksMonkey** [comment]
Aha!

The 'Speech to Ttext with Default Options' node, wasn't pulling the Default Locale from the project settings:
![image](https://user-images.githubusercontent.com/97111860/235540868-321ec0c0-31a7-460d-8320-ad24a751eadf.png)

Even though I specified the Default Locale in the AzSpeech Plugin's Project settings:
![image](https://user-images.githubusercontent.com/97111860/235540594-ceb09ee0-4506-41b8-ac57-0cbac045b773.png)

I figured this out by looking in the the Saved/Logs/AzSpeech log files and found a 400 error and the URL contained language=Default instead of language=en-US

Once I put the correct locale into the blueprint node, it worked perfectly:
![image](https://user-images.githubusercontent.com/97111860/235541431-1dba2d95-5d3c-43d7-9f02-832bf947502b.png)

So in my case, I think the bug is: "Speech to Text with Default Options does not use the Default Locale from Project Settings"

**Comment by gagallous** [comment]
Hello!
I'm using version 1.6.17 of this plugin downloaded from the Marketplace, I'm getting this error:
`UATHelper: Cooking (Windows): LogInit: Display: LogAzSpeech_Internal: Warning: LogLastError: Failed to load runtime library "../../../Engine/Plugins/Marketplace/AzSpeech/Source/ThirdParty/AzureWrapper/libs/Win/Runtime/Microsoft.CognitiveServices.Speech.extension.codec.dll": 2 (The system cannot find the file specified.).`

I'm using Unreal Engine version 5.3.2-29314046+++UE5+Release-5.3

This error is not allowing me to package my project, I read this issue but I couldn't find a solution, do you know what can I do to fix this? I tried a lot of stuff and still can't package my project while using this plugin.

Thank you.
