### ISSUE TITLE
speech to text with default options couldn't work

### ISSUE THREAD

**Issue by throb081** [lucoiso/UEAzSpeech#197]
Hello，i download the version  1.6.5.When i use "speech to text with default options " ,it can not work ,and i check the log i find the message:SpeechToText (88048); Function: StartAzureTaskWork; Message: Audio input device {0.0.1.00000000}.{INVALID_DEVICE} isn't available.But when i use the version 1.4.5,it can work well , i can not find out why /

**Comment by throb081** [comment]
Plus,i find that when i use the version 1.4.5 with OpenAi,metahuman plugin opened,it can not work either.It only work when there is only Azspeech plugin opening.I can not figure out why..

**Comment by lucoiso** [comment]
Hi! Sorry for the delay.

Can you try using the function Get Available Audio Input Devices and check the output to check the microphone? 

This error you sent occurs when there's no available mic to use.

If the return of the function I've mentioned contains 1 or more devices, can you try using the Device ID parameter?
