### ISSUE TITLE
TTS doesn't work, example project doesn't compile

### ISSUE THREAD

**Issue by faxcorp** [lucoiso/UEAzSpeech#200]
Hi. I can't open up the example project, I downloaded the archive from the releases section of the Example Project github page, when trying to open or compile I receive error: 
```
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command "C:\UE_5.1\Engine\Build\BatchFiles\Build.bat PluginsManagementEditor Win64 Development -Project="C:\Users\f4xw\Downloads\UEAzSpeechSampleProject-main\UEAzSpeechSampleProject-main\PluginsManagement.uproject" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "PluginsManagement.vcxproj" -- FAILED.
```

Can't find any info or tutorials. 
How does the TTS work if I just use Text To Speech with default settings node? Do I need to attach it to an audio component or something?
Also where to find the list of available voices? Can I leave None or Default?

**Comment by lucoiso** [comment]
Hi! Sorry for the delay!

Are there more information in the logs?

You can find the supported languages here: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support

The text to speech task will automatically convert the audio to sound wave and play in an internal audio component. But if you want to get the sound wave and play later or modify the settings, you can use the Text to Sound Wave task. :)

**Comment by lucoiso** [comment]
You will need to setup the default voice name and language in Project Settings -> Plugins -> AzSpeech
