### ISSUE TITLE
Speech to Text with Default Options won't work when Use Language Identification disabled since v1.6.4

### ISSUE THREAD

**Issue by kqkq** [lucoiso/UEAzSpeech#203]
v1.6.4 reorg the setting page, added a Use Language Identification option. However, the Speech to Text with Default Options feature won't work if the Use Language Identification is disabled. I have Locale and Candidate Languages properly set. Just disabled the Use Language Identification option will make recognition unusable.

the issue affects all versions after v.1.6.4.

Would you confirm the issue?

Thank you so much!

**Comment by lucoiso** [comment]
oops
