### ISSUE TITLE
(Multi-platform version) When packaging for Linux, binaries aren't found by default and need to be moved

### ISSUE THREAD

**Issue by kass-kass** [lucoiso/UEAzSpeech#209]
When packaging the plugin in a project for Linux, and running the `ProjectNames.sh` starting script, the following error is displayed:
```
error while loading shared libraries: libMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory
```

This issues comes frome the fact that all the Azure library files (`*.so`) are placed in `ProjectName\Binaries\Linux\ThirdParty\AzSpeech`. If the libraries are moved instead two folders up, to `ProjectName\Binaries\Linux`, the build starts up fine.

If there is a way to define where the libraries are placed when making a build, it would be great to fix this. I personally haven't found how this can be defined, but my knowledge of the UBT process isn't so deep.

**Comment by lucoiso** [comment]
Removed the sub directories, now the plugin binaries will be moved to the same directory of the executable: https://github.com/lucoiso/UEAzSpeech/commit/090480b3481f65cec455f9a447474114753a51e5#r124331032
