### ISSUE TITLE
Crash after TTS sound

### ISSUE THREAD

**Issue by Yak0vkaSup** [lucoiso/UEAzSpeech#215]
Hello again. I have got an issue that game crashes after tts prononciation here is the end of the logs before crash 
![image](https://github.com/lucoiso/UEAzSpeech/assets/113983099/cbcc0ff1-2768-4a2c-9bfb-027e655c31e0)
[UnrealExamples.log](https://github.com/lucoiso/UEAzSpeech/files/11574733/UnrealExamples.log)

**Comment by Yak0vkaSup** [comment]
And actually it crashes after speech recognition also. I tried custom settings, default settings but it crashes

**Comment by lucoiso** [comment]
Changed the broadcast of the result of synthesizer tasks: The tasks were never being ready to destroy and the unbind of the AudioComponent delegate was crashing the editor.
