### ISSUE TITLE
STT task sometimes causes ue editor to crash

### ISSUE THREAD

**Issue by fengbinlin** [lucoiso/UEAzSpeech#220]
STT task sometimes causes ue editor to crash
<img width="1926" alt="微信图片_20230720150254" src="https://github.com/lucoiso/UEAzSpeech/assets/94816363/bda0780b-3414-43c8-9f34-e52775e2ccc0">

**Comment by lucoiso** [comment]
Hi! Do you have more information about this crash? Can you send me the logs? :)

And I made some changes, if you can try again, let me know if this issue is still happening.
