### ISSUE TITLE
Azspeech crashes while running on ue

### ISSUE THREAD

**Issue by dada5872** [lucoiso/UEAzSpeech#234]
Azspeech crashes while running on ue
My ue version is 5.1
The operation steps are as follows
1. Add plugin, restarted
2. In the project settings section, Azspeech has been filled in and relevant content has been provided
3. In the blueprint section, just run a paragraph of text to have Azspeech generate a test voice
4. Directly crash after running

![image](https://github.com/lucoiso/UEAzSpeech/assets/69775612/e584d203-3c94-4b90-a04d-39b008a364ee)
![image](https://github.com/lucoiso/UEAzSpeech/assets/69775612/f0d87d68-eb60-47c1-b7b6-502a8f9748b1)
![image](https://github.com/lucoiso/UEAzSpeech/assets/69775612/131507e2-7362-47e1-a585-809ecd27b3e1)

**Comment by dada5872** [comment]
LoginId:c1577add4a397fa4ddd4f3abecf3e9f7
EpicAccountId:0438e05a71844c8a9c73f24c10280270

Unhandled Exception: 0xe06d7363

KERNELBASE
VCRUNTIME140
UnrealEditor_AzSpeech!__azac_handle_native_ex() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\AzSpeech\Source\ThirdParty\AzureWrapper\include\c_api\azac_debug.h:709]
UnrealEditor_AzSpeech!Microsoft::CognitiveServices::Speech::SpeechSynthesizer::FromConfig() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\AzSpeech\Source\ThirdParty\AzureWrapper\include\cxx_api\speechapi_cxx_speech_synthesizer.h:138]
UnrealEditor_AzSpeech!FAzSpeechSynthesisRunnable::InitializeAzureObject() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\AzSpeech\Source\AzSpeech\Private\AzSpeech\Runnables\Synthesis\AzSpeechSynthesisRunnable.cpp:190]
UnrealEditor_AzSpeech!FAzSpeechRunnableBase::Run() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\AzSpeech\Source\AzSpeech\Private\AzSpeech\Runnables\Bases\AzSpeechRunnableBase.cpp:60]
UnrealEditor_AzSpeech!FAzSpeechSynthesisRunnable::Run() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\AzSpeech\Source\AzSpeech\Private\AzSpeech\Runnables\Synthesis\AzSpeechSynthesisRunnable.cpp:21]
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll

**Comment by AlienZi** [comment]
I encountered the same problem

**Comment by dylantoo** [comment]
I encountered the same problem, how to fix it in ue5, thx

**Comment by pioneer518** [comment]
I also encountered the same problem. How to fix it in UE5? Thank you

**Comment by pioneer518** [comment]
Due to insufficient space on the C drive, the D drive was deleted and the space was given to the C drive. This error occurred after the operation. I restored the system and reinstalled software such as UE and VS, but the problem still persists.

**Comment by Anivia3013** [comment]
Do not put the modle under a chinese path!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
