### ISSUE TITLE
Synthesizers stopped working after Windows KB5018418 update

### ISSUE THREAD

**Issue by lucoiso** [lucoiso/UEAzSpeech#29]

**Comment by lucoiso** [comment]
The tasks are failing with this output: "USP error: timeout waiting for the first audio chunk".

There's a bug in the Microsoft's SDK: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1692

**Comment by TonyHenrique** [comment]
I am having this issue **Microsoft Windows [versão 10.0.22000.1098]**.

CANCELED: Reason=Error CANCELED: ErrorCode=ServiceTimeout CANCELED: ErrorDetails=[USP error: timeout waiting for the first audio chunk]

Is there a way to remove the KB5018418 update, while they release a fix for the Speech SDK Nuget Packages?

**Comment by fingerx** [comment]
if using win11,update 22h2, 22621.755  all is ok ,this ms bug
