### ISSUE TITLE
Convert Stream to Sound Wave doesn't work in a packaged game

### ISSUE THREAD

**Issue by tumi23** [lucoiso/UEAzSpeech#3]
When the game is packaged converting a stream to a Sound Wave and playing it doesn't seem to work even though it works in-engine, everything seems to be correctly converted but when playing the soundwave nothing plays. Text to voice does work though so its not that the plugin isn't functioning.

**Comment by lucoiso** [comment]
Hi @tumi23 !
_Sorry for the delay_

I'll take a look at that and update the plugin. Sorry for this issue, hope to fix it soon.
I will post updates here. : )

**Comment by tumi23** [comment]
I ended up modifying the plugin a bit on my end to get it working in a packaged build, the problem is the ConvertStreamToSoundWave() function where you used USoundWave::RawData but for some reason it doesn't seem to work in a packaged build while USoundWave::RawPCMData works, here's the thread to save you some digging 😃 [Thread](https://forums.unrealengine.com/t/loading-raw-wav-in-runtime-into-usoundwave/126017/6)

**Comment by lucoiso** [comment]
> Hey @lucoiso !
> 
> I ended up modifying the plugin a bit on my end to get it working in a packaged build, the problem is the ConvertStreamToSoundWave() function where you used USoundWave::RawData but for some reason it doesn't seem to work in a packaged build while USoundWave::RawPCMData works, here's the thread to save you some digging 😃 [Thread](https://forums.unrealengine.com/t/loading-raw-wav-in-runtime-into-usoundwave/126017/6)

This suggestion resolved this issue, thx to @tumi23 : )

Resolved: https://github.com/lucoiso/UEAzSpeech/pull/7
