### ISSUE TITLE
Question about spatialization support

### ISSUE THREAD

**Issue by motorsep** [lucoiso/UEAzSpeech#4]
This seems like a cool and useful plugin. I'd like to use it in my VR game to give voice to various NPCs. However, I am wondering if the output sound (text-2-speech or text-2-wav)  is going to be spatialized. I use Resonance Audio (or Oculus Audio) for mobile VR and Steam Audio for desktop VR.

How does the output from this plugin work (if at all) with spatial audio in UE4/5 ?

Thanks

**Comment by lucoiso** [comment]
Hey @motorsep ! : )
You can use:
1. Text-To-Stream + Convert Stream to Sound Wave
2. Text-To-WAV + Convert File to Sound Wave

And the returned Sound Wave can be used inside a AudioComponent or spawned at a determined location (Also can be used with a Sound Attenuation).

_If you encounter any bug, please feel free to reply_
