### ISSUE TITLE
How can I get the Viseme signal in line with the timing of the speech?

### ISSUE THREAD

**Issue by achumo6765** [lucoiso/UEAzSpeech#57]
How can I get the Viseme signal in line with the timing of the speech?

**Comment by michaelbecker-d** [comment]
Hi! Super curious about the Viseme pathway in general. Do you have an example to how it is consumed? I'm seeing the callback event (for example in the Text To Sound Wave node) but not sure where the data lives.
![image](https://user-images.githubusercontent.com/117380469/210302938-24059e09-477f-4c8b-83af-eed6a93ca969.png)

By the way, great job on this wrapper, @lucoiso - works smoothly and effortlessly. Really appreciated.

**Comment by michaelbecker-d** [comment]
Note to self and anyone looking for the same: check out this answer:
https://github.com/lucoiso/UEAzSpeech/issues/22#issuecomment-1304872135

(@lucoiso , feel free to correct me if the workflow has changed since)

**Comment by lucoiso** [comment]
Hi! @achumo6765 ! : )
Sorry for the delay!

The tasks have some getters that you can use while they're valid:

![image](https://user-images.githubusercontent.com/77353979/216349666-12fbaaa5-4eb0-4dd5-896c-5ee66e984807.png)
