### ISSUE TITLE
Crash occurring due to the plugin failing to create/delete Azure SDK Logs + Wrong loading of the libraries on Android builds

### ISSUE THREAD

**Issue by Ishu07** [lucoiso/UEAzSpeech#58]
I am attaching logs here
[stt.log](https://github.com/lucoiso/UEAzSpeech/files/10318543/stt.log)
### EDIT
Got it working on windows, but the same problem in android.

and exits with Abort message: 'terminating with uncaught exception of type std::runtime_error: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)
[device log.txt](https://github.com/lucoiso/UEAzSpeech/files/10321947/device.log.txt)

**Comment by lucoiso** [comment]
Created a new branch including ARM & ARM64 libraries for Android: https://github.com/lucoiso/UEAzSpeech/tree/hotfix/ANDROID-PACKAGING-ARM

**Comment by Ishu07** [comment]
> Created a new branch including ARM & ARM64 libraries for Android: https://github.com/lucoiso/UEAzSpeech/tree/hotfix/ANDROID-PACKAGING-ARM

I am trying again and reporting back, thanks

**Comment by Ishu07** [comment]
Still crashes, on the device output log, the first few lines are:

`D/UE      : In the JNI_OnLoad function 5
D/UE      : [GameActivity] java.lang.UnsatisfiedLinkError: dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.core.so" not found
D/UE      : [GameActivity] libMicrosoft.CognitiveServices.Speech.core library not loaded and may be required for AzSpeech.
D/UE      : [GameActivity] java.lang.UnsatisfiedLinkError: dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.extension.audio.sys.so" not found
D/UE      : [GameActivity] libMicrosoft.CognitiveServices.Speech.extension.audio.sys library not loaded and may be required for AzSpeech.
D/UE      : [GameActivity] java.lang.UnsatisfiedLinkError: dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.extension.kws.so" not found
D/UE      : [GameActivity] libMicrosoft.CognitiveServices.Speech.core library not loaded and may be required for AzSpeech.
D/UE      : [GameActivity] java.lang.UnsatisfiedLinkError: dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.extension.lu.so" not found
D/UE      : [GameActivity] libMicrosoft.CognitiveServices.Speech.extension.lu library not loaded and may be required for AzSpeech.
D/UE      : Entering native app glue main function
D/UE      : Created event thread
D/UE      : Entered AndroidMain()
`

**Comment by lucoiso** [comment]
@Ishu07

Looks like the libs wasn't copied to the build folder. I've updated the Android UPL in the last commit. 

```
dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.core.so" not found
```

Can you check again? And can you check if the same problem occurs with "Enable Azure SDK Logs" disabled in Project Settings? Perhaps the plugin is not able to create the log file in Android environments and the failure is occurring because the file does not exist and there is nowhere to write the log.

**Comment by lucoiso** [comment]
New branch w/ SDK logs disabled for android: https://github.com/lucoiso/UEAzSpeech/tree/hotfix/LOG-GENERATION-CRASH

**Comment by ocinon** [comment]
The issue still exists for me under UE5.1 for Android (shipping build with GooglePAD enabled, target SDK 31). During the build process I get:

`LogAzSpeech_Internal: Warning: LoadDependency: Failed to load library ../../../../../Projects/X/Plugins/AzSpeech/Source/ThirdParty/AzureWrapper/libs/Win/Runtime/Microsoft.CognitiveServices.Speech.extension.codec.dll.`

It does copy the .so files to `Intermediate/Android/arm64/libs/arm64-v8a` and then `Intermediate\Android\gradle\app\src\main\libs\arm64-v8a` though.

When running it, the application starts visually fine, but throws this during startup:

```
[GameActivity] java.lang.UnsatisfiedLinkError: dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.core.so" not found
[GameActivity] libMicrosoft.CognitiveServices.Speech.core library not loaded and may be required for AzSpeech.
[GameActivity] java.lang.UnsatisfiedLinkError: dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.extension.audio.sys.so" not found
[GameActivity] libMicrosoft.CognitiveServices.Speech.extension.audio.sys library not loaded and may be required for AzSpeech.
[GameActivity] java.lang.UnsatisfiedLinkError: dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.extension.kws.so" not found
[GameActivity] libMicrosoft.CognitiveServices.Speech.core library not loaded and may be required for AzSpeech.
[GameActivity] java.lang.UnsatisfiedLinkError: dlopen failed: library "liblibMicrosoft.CognitiveServices.Speech.extension.lu.so" not found
[GameActivity] libMicrosoft.CognitiveServices.Speech.extension.lu library not loaded and may be required for AzSpeech.
```

and then crashes the moment any STT function is called (every time). Any ideas?

**Comment by lucoiso** [comment]
Hello! @ocinon : )

_library "liblibMicrosoft..._
A extra "lib" was added to the filenames wtf 👀

I'll take a look at this issue, thanks for the information!

If you want to test locally: there's a file called *AzSpeech_UPL_Android.xml* that's responsible for the copy and load of the dependencies on Android. You can test removing the "lib" from the front of the filenames in the soLoadLibrary section.

I'll check this soon and test the behavior with other engine versions!

**Comment by ocinon** [comment]
@lucoiso thanks so much for the quick response! Your hotfix did indeed solve that issue!

Sadly, it hasn't solved the actual crash. A "DebugGame" build works on Android, but a development or shipping build crashes any time the STT function is called. I also can't find any usable exception or error, I assume they all symbols are stripped during distribution.

```
System.exit called, status: 0
I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
[...]
E/TheiaManager: [tagL]: calling catchLog()..., focusedPid:7499 pids:[7499]
D/TheiaManager: No stackTrace found in args
```

I am wondering whether this is a shipping build issue on Android or has something to do with GooglePAD/the Google play store distribution.

**Comment by ocinon** [comment]
Even with GooglePAD and distribution disabled and when deployed locally, the Android build crashes during the STT call when it is a shipping build. It works with Debug and Development builds.

**Comment by lucoiso** [comment]
@ocinon created a separated issue and will start the works as soon as possible! : )

https://github.com/lucoiso/UEAzSpeech/issues/70

**Comment by lucoiso** [comment]
Merged in development branch: https://github.com/lucoiso/UEAzSpeech/tree/development

New issue: https://github.com/lucoiso/UEAzSpeech/issues/70
