### ISSUE TITLE
Packaging failing for Android

### ISSUE THREAD

**Issue by lucoiso** [lucoiso/UEAzSpeech#62]
From forum's post: https://forums.unrealengine.com/t/free-azspeech-plugin-text-to-speech-speech-to-text-and-more-with-microsoft-azure-cognitive-services/495394/109?u=lucoiso

> [R3D9477](https://forums.unrealengine.com/u/R3D9477)
> Hello. Something went worng during compilation for Android device:
> 
> ```
> LogPlayLevel: [1/2] clang++ MyMobileInterlocutor-armv7.so
> LogPlayLevel: Error: ld.lld: error: Plugins/UEAzSpeech/Source/ThirdParty/AzureWrapper/libs/Android/libMicrosoft.CognitiveServices.Speech.core.so is incompatible with armelf_linux_eabi
> LogPlayLevel: Error: ld.lld: error: Plugins/UEAzSpeech/Source/ThirdParty/AzureWrapper/libs/Android/libMicrosoft.CognitiveServices.Speech.extension.audio.sys.so is incompatible with armelf_linux_eabi
> LogPlayLevel: Error: ld.lld: error: Plugins/UEAzSpeech/Source/ThirdParty/AzureWrapper/libs/Android/libMicrosoft.CognitiveServices.Speech.extension.kws.so is incompatible with armelf_linux_eabi
> LogPlayLevel: Error: ld.lld: error: Plugins/UEAzSpeech/Source/ThirdParty/AzureWrapper/libs/Android/libMicrosoft.CognitiveServices.Speech.extension.lu.so is incompatible with armelf_linux_eabi
> LogPlayLevel: Error: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> What is the target architecture of the libs are using for Android ?

> [R3D9477](https://forums.unrealengine.com/u/R3D9477)
> solved by replacing libs in Android/* with libs from Linux/arm32/*

**Comment by lucoiso** [comment]
Could not reproduce this issue yet.
Initially testing with UE5.1 ant the plugin version from master branch.

_The plugin is compiling normally here and in the UE Marketplace team's enviroment (they test the building before allowing the publish)._

I'll continue try to reproduce this issue using different engine and VS versions!

Last output:

```
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): Package command time: 15.93 s
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): ********** PACKAGE COMMAND COMPLETED **********
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): ********** ARCHIVE COMMAND STARTED **********
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): Archiving to D:/lucas/Desktop/Packaging Test
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): Target: x86_64-w64-windows-gnu
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): Thread model: posix
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): InstalledDir: C:/Users/lucas/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): GetPackageInfo ReturnValue: com.YourCompany.PluginsManagement
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): GetPackageInfo ReturnValue: 1
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): GetPackageInfo ReturnValue: com.YourCompany.PluginsManagement
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): GetPackageInfo ReturnValue: 1
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): GetPackageInfo ReturnValue: com.YourCompany.PluginsManagement
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): GetPackageInfo ReturnValue: 1
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): GetPackageInfo ReturnValue: com.YourCompany.PluginsManagement
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): GetPackageInfo ReturnValue: 1
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): Archive command time: 0.22 s
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): ********** ARCHIVE COMMAND COMPLETED **********
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): BuildCookRun time: 32.88 s
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): BUILD SUCCESSFUL
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): AutomationTool executed for 0h 0m 33s
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): AutomationTool exiting with ExitCode=0 (Success)
```

**Comment by lucoiso** [comment]
Created a new branch including ARM & ARM64 libraries for Android: https://github.com/lucoiso/UEAzSpeech/tree/hotfix/ANDROID-PACKAGING-ARM

**Comment by Fansi129** [comment]
Same issue. 
Tried latest version from GitHub and marketplace. Does not package for android in 4.27.

**Comment by lucoiso** [comment]
Target.Architecture is always returning empty string when building for Android. Because of this behavior, UE4.27 was trying to add arm64-v8 libs to armeabi-v7 architecture.
