### ISSUE TITLE
LogAzSpeech: Error: Task: TextToSoundWave (295846); Function: Activate; Message: Failed to activate task

### ISSUE THREAD

**Issue by mkygogo** [lucoiso/UEAzSpeech#86]
test the node "Text to Sound Wave" got this error:
LogAzSpeech: Error: Task: TextToSoundWave (295846); Function: Activate; Message: Failed to activate task

**Comment by lucoiso** [comment]
Hello! @mkygogo  : )

Can you enable the option "Enable Internal Logs" in Project Settings -> Plugins -> AzSpeech and send me the output log?

The logs will be printed in the Output Log inside the engine and also in the file located at PROJECT_FOLDER/Saved/Logs

**Comment by mkygogo** [comment]
LogAzSpeech: Display: Task: TextToSoundWave (342078); Function: Activate; Message: Activating task
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: StartAzureTaskWork; Message: Starting Azure SDK task
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: StartAzSpeechRunnableTask; Message: Creating new runnable thread to initialize work
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: Init; Message: Initializing runnable thread
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: CanInitializeTask; Message: Checking if can initialize task in current context
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: Run; Message: Running runnable thread work
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: InitializeAzureObject; Message: Initializing Azure Object
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: InitializeAzureObject; Message: Creating synthesizer object
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: CreateSpeechConfig; Message: Creating Azure SDK speech config
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: ApplySDKSettings; Message: Applying Azure SDK Settings
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: EnableLogInConfiguration; Message: Enabling Azure SDK log
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: ApplySDKSettings; Message: Using language: zh-TW
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: ApplySDKSettings; Message: Using voice: zh-TW-HsiaoChenNeura
LogAzSpeech_Internal: Display: Task: TextToSoundWave (342078); Function: Run; Message: Starting synthesis.
LogAzSpeech_Internal: Error: Task: TextToSoundWave (342078); Function: ProcessSynthesisResult; Message: Task failed. Reason: Canceled
LogAzSpeech_Internal: Error: Task: TextToSoundWave (342078); Function: ProcessSynthesisResult; Message: Cancellation Reason: Error
LogAzSpeech_Internal: Error: Task: TextToSoundWave (342078); Function: ProcessCancellationError; Message: Error code: BadRequest

**Comment by mkygogo** [comment]
and the ue editor crashed...

**Comment by mkygogo** [comment]
this is my setting

![1675343106020](https://user-images.githubusercontent.com/34338922/216332732-d472a1ba-1434-466a-acdd-08cae447898f.png)

**Comment by lucoiso** [comment]
@mkygogo 
Can you send me the SDK logs? You can find it inside: PROJECT_FOLDER/Saved/Logs/AzSpeech

**Comment by lucoiso** [comment]
@mkygogo 
Ahh, can you check the VoiceName?

Is the 'l' missing from the end of the name or is it just not showing in the image? **zh-TW-HsiaoChenNeura** => **zh-TW-HsiaoChenNeural**

**Comment by mkygogo** [comment]
[UEAzSpeech 2023.02.02-21.30.26.log](https://github.com/lucoiso/UEAzSpeech/files/10569435/UEAzSpeech.2023.02.02-21.30.26.log)

**Comment by mkygogo** [comment]
> 

thank you ,it's my fault, I just missed the letter "l"

**Comment by C852062** [comment]
[AzSpeech 2023.07.19-22.51.37.log](https://github.com/lucoiso/UEAzSpeech/files/12096357/AzSpeech.2023.07.19-22.51.37.log)

**Comment by C852062** [comment]
Why do I always fail to activate
